# START HERE: change your name and the short site description.
project:
  type: website
  output-dir: docs
  resources: 
    - "Gun_Control_Project.pdf"
  render:
    - "*.qmd"
    - "posts/*.qmd"

# The appearance lives here. Usually leave this line alone.
metadata-files:
  - _design/defaults.yml

website:
  title: "Juliana Santucci"
  description: "An undergraduate political science student with an applied data analysis minor" # Later, when published, uncomment and replace the address below.
  # site-url: "https://YOUR-USERNAME.github.io/YOUR-REPOSITORY/"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Career
        href: career.qmd
      - text: Travel
        href: travel.qmd 
      
        
  